<a href="https://colab.research.google.com/github/Douglas-v/python_senai_2024/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#analise para produção de goiaba

w1, w2, w3 = 0.3, 0.2, 0.5

print(w1)
print(w2)
print(w3)

0.3
0.2
0.5


In [ ]:
#dados da região A
regiaoA_temp = 22
regiaoA_chuva = 67
regiaoA_umid = 65

#aplicando no modelos
reiaoA_goiaba = regiaoA_temp*w1 + regiaoA_chuva*w2 + regiaoA_umid*w3
print('Na região A, a produção de goiaba é de',reiaoA_goiaba,'toneladas por hectare.')

Na região A, a produção de goiaba é de 52.5 toneladas por hectare.


In [ ]:
#Fazendo com lista

regiaoA = [22, 67, 65]
regiaoB = [24, 88, 95]
regiaoC = [17, 134, 50]
regiaoD = [18, 96, 70]

pesos = [w1, w2, w3]

In [ ]:
def producao_goiaba(regiao, pesos):
  result = 0
  for x, w in zip(regiao, pesos):
    result += x*w
  return result


In [ ]:
  #produção da regiao A
  print(producao_goiaba(regiaoA, pesos))

  #produção regiao B
  print(producao_goiaba(regiaoB,pesos))

    #produção regiao C
  print(producao_goiaba(regiaoC,pesos))

    #produção regiao D
  print(producao_goiaba(regiaoD,pesos))

52.5
72.3
56.9
59.6


In [ ]:
#usando numpy - pode-se digitar os valores completos, mas como já declarei anteriormente, só vou converter

import numpy as np

regiaoA_ = np.array(regiaoA)
pesos_ = np.array(pesos)

print(type(regiaoA_))
print(type(pesos_))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
reg_a = np.dot(regiaoA_,pesos_)
print('Regiao A:',reg_a)

Regiao A: 52.5


In [ ]:
#Exemplo - APlicando Numpy

#lista Python
arr1 = list(range(2000000))
arr2 = list(range(1000000,3000000))

#vetor em Numpy
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [ ]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
  result += x1*x2
print(result)

4666663666667000000
CPU times: user 418 ms, sys: 0 ns, total: 418 ms
Wall time: 419 ms


In [ ]:
%%time
print(np.dot(arr1_np,arr2_np))

4666663666667000000
CPU times: user 6.8 ms, sys: 0 ns, total: 6.8 ms
Wall time: 7.88 ms


In [ ]:
#Matrizes
dados_climaticos = np.array([[22,67,65],[22,88,95],[17,134,50],[18,96,70],])
print(dados_climaticos)

[[ 22  67  65]
 [ 22  88  95]
 [ 17 134  50]
 [ 18  96  70]]


In [ ]:
#Matriz 3D
arr3 = np.array([[[11,12,13],[13,1,15]],
                [[15,16,17],[17,18,19.5]]])
print(arr3.shape)

(2, 2, 3)


In [ ]:
print(pesos_.dtype)
print("--------")
print(dados_climaticos.dtype)

float64
--------
int64


In [ ]:
#Realizar as operações com matmul (@)
np.matmul(dados_climaticos, pesos_)
dados_climaticos @ pesos_

array([52.5, 71.7, 56.9, 59.6])

In [ ]:
goiaba_csv = np.genfromtxt('/content/Pasta1.csv',delimiter=',',skip_header=1)
goiaba_csv


array([[24., 20., 21.],
       [18., 23., 16.],
       [19., 30., 36.]])

In [ ]:
pesos_ = np.array([0.4,0.2,0.8])

rendimento = goiaba_csv@pesos_

rendimento

array([30.4, 24.6, 42.4])

In [ ]:
#Incluindo o resultado na Matriz

resultado = np.concatenate((goiaba_csv,rendimento.reshape(3,1)),axis=1)
resultado

array([[24. , 20. , 21. , 30.4],
       [18. , 23. , 16. , 24.6],
       [19. , 30. , 36. , 42.4]])

In [ ]:
np.savetxt('goiaba_resultado.csv',
           resultado,
           fmt='%.2f',
           delimiter=',',
           header='temperatura, precipitação, umidade, rendimento',
           comments='')

In [ ]:
arr2 = np.array([[2,2,3,4],[5,6,7,6],[9,1,2,3]])
arr3 = np.array([[11,13,13,14],[10,16,17,18],[19,11,12,10]])

arr2 + 3 #Soma/subtração de escalar

arr2 * arr3 #multiplicação/divisão entre matrizes

arr2 / 2 #multiplicação/divisão de escalar

array([[1. , 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 3. ],
       [4.5, 0.5, 1. , 1.5]])

In [ ]:
arr1 = np.array([[1,1,1],[3,4,5]])
arr2 = np.array([[2,1,3],[1,1,1]])

arr1 == arr2

arr1 != arr2

arr1 > arr2

arr1 <= arr2

array([[ True,  True,  True],
       [False, False, False]])